// Batch demo fixtures generated by the TypeScript/React side and exported as a list of valid RV
// documents. The consumer side imports each document with the Rust WebAssembly engine.

export type BatchRvType = 'continuous' | 'discrete'

export interface BatchItem {
  id: string
  label: string
  type: BatchRvType
  doc: {
    format_version: string
    metadata?: Record<string, unknown>
    rv: unknown
  }
}

export const BATCH_ITEMS: BatchItem[] = [
  {
    id: 'normal_shifted',
    label: 'Normal process noise',
    type: 'continuous',
    doc: {
      format_version: '1.0.0',
      metadata: { name: 'normal_process_noise', units: 'a.u.' },
      rv: { kind: 'leaf', dist: 'normal', params: { mu: 2, sigma: 0.8 } },
    },
  },
  {
    id: 'weibull_strength',
    label: 'Weibull fracture strength',
    type: 'continuous',
    doc: {
      format_version: '1.0.0',
      metadata: { name: 'weibull_fracture_strength', units: 'MPa' },
      rv: { kind: 'leaf', dist: 'weibull', params: { shape: 10, scale: 350 } },
    },
  },
  {
    id: 'categorical_die',
    label: 'Categorical inspection class',
    type: 'discrete',
    doc: {
      format_version: '1.0.0',
      metadata: { name: 'inspection_class' },
      rv: {
        kind: 'leaf',
        dist: 'categorical',
        params: { categories: [1, 2, 3, 4], probs: [0.1, 0.2, 0.45, 0.25] },
      },
    },
  },
  {
    id: 'mixture_bimodal',
    label: 'Bimodal grain size',
    type: 'continuous',
    doc: {
      format_version: '1.0.0',
      metadata: { name: 'bimodal_grain_size' },
      rv: {
        kind: 'mixture',
        weights: [0.7, 0.3],
        components: [
          { kind: 'leaf', dist: 'lognormal', params: { mu: 1, sigma: 0.3 } },
          { kind: 'leaf', dist: 'lognormal', params: { mu: 2.5, sigma: 0.4 } },
        ],
      },
    },
  },
  {
    id: 'transform_exp_normal',
    label: 'exp(Normal) transform',
    type: 'continuous',
    doc: {
      format_version: '1.0.0',
      metadata: { name: 'exp_normal_transform' },
      rv: {
        kind: 'transform',
        base: { kind: 'leaf', dist: 'normal', params: { mu: 0, sigma: 1 } },
        op: { name: 'exp' },
      },
    },
  },
]

export function buildRvListBundle(items: { id: string; label: string; type: BatchRvType; document: unknown }[]) {
  return {
    format_version: '1.0.0',
    kind: 'rv_list',
    producer: { language: 'TypeScript', framework: 'Next.js/React' },
    consumer: { language: 'Rust', framework: 'WebAssembly worker' },
    items,
  }
}
