#!/usr/bin/env python3
"""Build the evidence pack (`evidence/EVIDENCE.md`).

Runs the per-language reporters (Python / TypeScript / Rust), each of which re-derives every
conformance value against the shared golden and micro-benchmarks the hot paths, then renders the
3×N conformance matrix, a cross-language timing table, the Big-O table, and reproduction commands.

Like `conformance/generate.py`, this is a thin client: it contains no distribution math - it only
aggregates what the three implementations report. Run from the repo root:

    PYTHONPATH=impl/python/src python3 evidence/build_evidence.py
"""

# Core
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOL = 1e-9

REPORTERS = [
    ("Python", [sys.executable, "evidence/report.py"], ROOT),
    ("TypeScript", ["npx", "tsx", "evidence/report.ts"], ROOT),
    ("Rust", ["cargo", "run", "--release", "--quiet", "--example", "report"], os.path.join(ROOT, "impl", "rust")),
]


def run_reporter(name, cmd, cwd):
    env = dict(os.environ, PYTHONPATH=os.path.join(ROOT, "impl", "python", "src"))
    out = subprocess.run(cmd, cwd=cwd, env=env, capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"reporter {name} failed:\n{out.stderr}")
    return json.loads(out.stdout.strip().splitlines()[-1])


def fmt_err(e):
    return "0" if e == 0 else f"{e:.0e}"


def cell(rep_case):
    if rep_case is None:
        return "n/a"
    if rep_case["comparisons"] == 0:
        return "-"
    mark = "✓" if rep_case["max_abs_error"] <= TOL else "✗"
    return f"{mark} {fmt_err(rep_case['max_abs_error'])}"


def matrix(reports):
    langs = [r["language"] for r in reports]
    by_lang = {r["language"]: {c["name"]: c for c in r["cases"]} for r in reports}
    names = [c["name"] for c in reports[0]["cases"]]

    header = "| case | " + " | ".join(f"{l} max\\|err\\|" for l in langs) + " |"
    sep = "|" + "---|" * (len(langs) + 1)
    rows = []
    for name in names:
        cells = " | ".join(cell(by_lang[l].get(name)) for l in langs)
        rows.append(f"| `{name}` | {cells} |")

    total = sum(c["comparisons"] for c in reports[0]["cases"])
    worst = {l: max((c["max_abs_error"] for c in by_lang[l].values() if c["comparisons"]), default=0.0) for l in langs}
    return header, sep, rows, total, worst, langs


def timings_table(reports):
    metrics = [
        ("sample_ns_per_draw", "sample (ns / draw)"),
        ("normal_log_prob_ns", "normal log_prob (ns / call)"),
        ("gamma_cdf_ns", "gamma cdf (ns / call)"),
    ]
    langs = [r["language"] for r in reports]
    t = {r["language"]: r["timings"] for r in reports}
    lines = ["| metric | " + " | ".join(langs) + " |", "|" + "---|" * (len(langs) + 1)]
    for key, label in metrics:
        cells = " | ".join(f"{t[l][key]:.1f}" for l in langs)
        lines.append(f"| {label} | {cells} |")
    return "\n".join(lines)


BIG_O = """\
| kind | sample | log_prob |
|---|---|---|
| Leaf analytic | O(1) | O(1) |
| Leaf categorical (k) | O(1) draw after O(k) build | O(1) |
| Leaf empirical (n) | O(1) draw | O(n) per query (KDE) |
| Joint (d dims) | O(d) + children | O(d) + children |
| Mixture (k comps) | O(1) component (alias) + child | O(k) + children (logsumexp) |
| Transform | O(child) | O(child) + O(1) Jacobian |"""


def render(reports):
    header, sep, rows, total, worst, langs = matrix(reports)
    worst_overall = max(worst.values())
    versions = ", ".join(f"{r['language']} {r['version']}" for r in reports)

    return f"""# RV Exchange - Evidence Pack

Auto-generated by `evidence/build_evidence.py` ({versions}). Each implementation independently
re-derives every conformance value against the shared golden (produced by scipy, the trusted
reference) and reports the worst absolute deviation. **Do not edit by hand.**

## 1. Reliability - cross-language conformance (3 × {len(rows)})

Every deterministic output (`log_prob`, `cdf`, closed-form `moments`) of all {len(rows)} conformance
cases, recomputed by each implementation and compared to golden. Cells show `max |impl − golden|`
over that case's control points; `-` marks sampling-only cases (no deterministic golden, e.g. the
non-invertible `abs` transform). Tolerance is **1e-9**.

{header}
{sep}
{chr(10).join(rows)}

- **{total} deterministic values** per language; worst deviation across all three:
  **{fmt_err(worst_overall)}** (≤ 1e-9). Same `.rv.json` ⇒ same numbers in Python, TypeScript, and Rust.
- Python *produced* the golden (via scipy), so its column is `0` by construction. The meaningful
  evidence is that **TypeScript and Rust are independent re-implementations** - different special-function
  code, different RNG, no shared math - and still agree with that golden within 1e-9.

## 2. Reliability - property tests

Beyond fixed golden values, each implementation runs property-based tests (Hypothesis / fast-check /
proptest):

- **Round-trip identity** - `parse → serialize → parse → serialize` is idempotent (canonical form).
- **Sampling ↔ CDF (Kolmogorov-Smirnov)** - samples drawn from a reconstructed RV agree with its own
  CDF (KS statistic below threshold), proving the format preserves *semantics*, not just bytes.
- **Validation rejections** - bad mixture weights, declared-capability mismatch, and invalid
  parameters are rejected.

## 3. Scalability & speed - timings

Hot-path micro-benchmarks (representative, single machine). Sampling is the comparable metric across
languages; the evaluate paths differ in style (Python is vectorized via numpy/scipy in C, while
TypeScript and Rust evaluate scalars in tight loops), so read those rows per-language, not as a race.

{timings_table(reports)}

The Rust core also compiles to `wasm32-unknown-unknown` (~337 KB), so the same verified engine runs
natively, in Node, and in the browser (the demo samples in a Web Worker).

## 4. Complexity (Big-O)

{BIG_O}

The structure/bulk split (empirical samples in a base64/`.npy` sidecar) keeps structural parse time
independent of sample count.

## 5. Reproduce

```bash
# Conformance suites (each asserts agreement @1e-9):
cd impl/python && PYTHONPATH=src python3 -m pytest
cd impl/typescript && npm test
cd impl/rust && cargo test

# Regenerate this pack:
PYTHONPATH=impl/python/src python3 evidence/build_evidence.py
```
"""


def main():
    reports = [run_reporter(*r) for r in REPORTERS]
    out_path = os.path.join(ROOT, "evidence", "EVIDENCE.md")
    with open(out_path, "w") as f:
        f.write(render(reports))
    print(f"Wrote {out_path}")

    # Fail (for CI) if any implementation disagrees with golden beyond tolerance.
    failures = [
        f"{r['language']}/{c['name']}: {c['max_abs_error']:.2e}"
        for r in reports
        for c in r["cases"]
        if c["comparisons"] and c["max_abs_error"] > TOL
    ]
    if failures:
        sys.exit("conformance mismatch (> 1e-9):\n  " + "\n  ".join(failures))
    print(f"All implementations agree within {TOL:g}.")


if __name__ == "__main__":
    main()
